<?php

session_start();

require_once("../includes/permissions.php");
requireRole(['Manager']);

if (!isset($_SESSION['username'])) {
    header("Location: ../auth/login.php");
    exit();
}

include("../config/db.php");


/* ==============================
   Search
================================ */

$search = "";

if (isset($_GET['search'])) {

    $search = mysqli_real_escape_string(
        $conn,
        $_GET['search']
    );

}


/* ==============================
   Machine Query
================================ */

$sql = "
SELECT
    machines.asset_number,
    customers.customer_name,
    machines.brand,
    machines.machine_model,
    machines.serial_number,
    machines.location,
    machines.status,
    machines.installation_date

FROM machines

LEFT JOIN customers
    ON machines.customer_id = customers.id

WHERE
    machines.asset_number LIKE '%$search%'
    OR customers.customer_name LIKE '%$search%'
    OR machines.machine_model LIKE '%$search%'
    OR machines.brand LIKE '%$search%'
    OR machines.serial_number LIKE '%$search%'

ORDER BY machines.asset_number ASC
";


$result = mysqli_query($conn, $sql);


if (!$result) {

    die("Database error: " . mysqli_error($conn));

}


/* ==============================
   Excel Headers
================================ */

header("Content-Type: application/vnd.ms-excel");

header(
    "Content-Disposition: attachment; filename=machine_report.xls"
);

header("Pragma: no-cache");
header("Expires: 0");


/* ==============================
   Report Header
================================ */

echo "G3 Systems - Machine Report\n";

echo "Generated By: "
    . $_SESSION['full_name']
    . "\n";

echo "Generated On: "
    . date("d F Y h:i A")
    . "\n";

echo "\n";


/* ==============================
   Column Headers
================================ */

echo "Asset No.\tCustomer\tBrand\tModel\tSerial No.\tLocation\tStatus\tInstalled\n";


/* ==============================
   Machine Data
================================ */

while ($row = mysqli_fetch_assoc($result)) {

    echo
        $row['asset_number'] . "\t" .
        $row['customer_name'] . "\t" .
        $row['brand'] . "\t" .
        $row['machine_model'] . "\t" .
        $row['serial_number'] . "\t" .
        $row['location'] . "\t" .
        $row['status'] . "\t" .
        $row['installation_date'] . "\n";
}

exit();

?>