<?php

session_start();

require_once("../includes/permissions.php");
requireRole(['Manager']);

if (!isset($_SESSION['username'])) {
    header("Location: ../auth/login.php");
    exit();
}

include("../config/db.php");


// ==============================
// Excel Headers
// ==============================

header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=job_card_report.xls");
header("Pragma: no-cache");
header("Expires: 0");


// ==============================
// Search
// ==============================

$search = "";

if (isset($_GET['search'])) {

    $search = mysqli_real_escape_string(
        $conn,
        $_GET['search']
    );

}


// ==============================
// Job Card Query
// ==============================

$sql = "SELECT

            job_cards.*,
            customers.customer_name,
            machines.asset_number,
            technicians.full_name

        FROM job_cards

        LEFT JOIN customers
            ON job_cards.customer_id = customers.id

        LEFT JOIN machines
            ON job_cards.machine_id = machines.id

        LEFT JOIN technicians
            ON job_cards.technician_id = technicians.id

        WHERE

            job_cards.job_card_number LIKE '%$search%'
            OR customers.customer_name LIKE '%$search%'
            OR machines.asset_number LIKE '%$search%'
            OR technicians.full_name LIKE '%$search%'
            OR job_cards.status LIKE '%$search%'

        ORDER BY job_cards.created_at DESC";


$result = mysqli_query($conn, $sql);


// ==============================
// Report Information
// ==============================

echo "G3 Systems - Job Card Report\n";

echo "Generated By: "
     . $_SESSION['full_name']
     . "\n";

echo "Generated On: "
     . date("d F Y h:i A")
     . "\n";

echo "\n";


// ==============================
// Table Headers
// ==============================

echo "Job Card\tCustomer\tAsset No.\tTechnician\tStatus\tCreated\n";


// ==============================
// Data
// ==============================

while ($row = mysqli_fetch_assoc($result)) {

    echo
        $row['job_card_number'] . "\t" .
        $row['customer_name'] . "\t" .
        $row['asset_number'] . "\t" .
        $row['full_name'] . "\t" .
        $row['status'] . "\t" .
        date("d M Y", strtotime($row['created_at'])) .
        "\n";
}

?>