<?php

session_start();

require_once("../includes/permissions.php");
requireRole(['Manager']);

if (!isset($_SESSION['username'])) {
    header("Location: ../auth/login.php");
    exit();
}

include("../config/db.php");


/* ==============================
   Search
================================ */

$search = "";

if (isset($_GET['search'])) {

    $search = mysqli_real_escape_string(
        $conn,
        $_GET['search']
    );

}


/* ==============================
   Customer Query
================================ */

$sql = "
SELECT
    id,
    customer_name,
    company_name,
    phone,
    email,
    address
FROM customers
WHERE
    customer_name LIKE '%$search%'
    OR company_name LIKE '%$search%'
    OR phone LIKE '%$search%'
    OR email LIKE '%$search%'
ORDER BY customer_name ASC
";

$result = mysqli_query($conn, $sql);

if (!$result) {

    die("Database error: " . mysqli_error($conn));

}


/* ==============================
   Excel Headers
================================ */

header("Content-Type: application/vnd.ms-excel");

header(
    "Content-Disposition: attachment; filename=customer_report.xls"
);

header("Pragma: no-cache");
header("Expires: 0");


/* ==============================
   Excel Report
================================ */

echo "G3 Systems - Customer Report\n";
echo "Generated By: " . $_SESSION['full_name'] . "\n";
echo "Generated On: " . date("d F Y h:i A") . "\n";
echo "\n";

echo "ID\tCustomer Name\tCompany\tPhone\tEmail\tAddress\n";


/* ==============================
   Customer Data
================================ */

while ($row = mysqli_fetch_assoc($result)) {

    echo
        $row['id'] . "\t" .
        $row['customer_name'] . "\t" .
        $row['company_name'] . "\t" .
        $row['phone'] . "\t" .
        $row['email'] . "\t" .
        $row['address'] . "\n";
}

exit();

?>