<?php
session_start();
require_once("../includes/permissions.php");
requireRole(['Manager']);

if (!isset($_SESSION['username'])) {
    header("Location: ../auth/login.php");
    exit();
}

include("../config/db.php");
/* Load Company Settings */

$settings_result = mysqli_query($conn, "SELECT * FROM settings WHERE id=1");
$settings = mysqli_fetch_assoc($settings_result);

$company_name = $settings['company_name'] ?? "G3 Systems";
$company_phone = $settings['company_phone'] ?? "";
$company_email = $settings['company_email'] ?? "";
$company_address = $settings['company_address'] ?? "";
include("../includes/header.php");
include("../includes/sidebar.php");
include("../includes/status_badge.php");

$search = "";

if (isset($_GET['search'])) {
    $search = mysqli_real_escape_string($conn, $_GET['search']);
}

$sql = "SELECT
            job_cards.*,
            customers.customer_name,
            machines.asset_number,
            technicians.full_name

        FROM job_cards

        LEFT JOIN customers
        ON job_cards.customer_id = customers.id

        LEFT JOIN machines
        ON job_cards.machine_id = machines.id

        LEFT JOIN technicians
        ON job_cards.technician_id = technicians.id

        WHERE

        job_cards.job_card_number LIKE '%$search%'
        OR customers.customer_name LIKE '%$search%'
        OR machines.asset_number LIKE '%$search%'
        OR technicians.full_name LIKE '%$search%'
        OR job_cards.status LIKE '%$search%'

        ORDER BY job_cards.created_at DESC";

$result = mysqli_query($conn, $sql);

$total = mysqli_query($conn, "SELECT COUNT(*) AS total FROM job_cards");
$totalJobCards = mysqli_fetch_assoc($total);
?>

<div class="main-content">
    
<div class="report-header">

<img src="../assets/images/logo.png">

<h2><?php echo htmlspecialchars($company_name); ?></h2>

<h3>Service Management System</h3>

<?php if($company_phone != ""): ?>
<p>📞 <?php echo htmlspecialchars($company_phone); ?></p>
<?php endif; ?>

<?php if($company_email != ""): ?>
<p>✉️ <?php echo htmlspecialchars($company_email); ?></p>
<?php endif; ?>

<?php if($company_address != ""): ?>
<p>📍 <?php echo htmlspecialchars($company_address); ?></p>
<?php endif; ?>

<hr>

</div>

<h1>Job Card Report</h1>

<p>
<strong>Generated On:</strong>
<?php echo date("d F Y"); ?>
|
<?php echo date("h:i A"); ?>
<br>

<strong>Generated By:</strong>
<?php echo $_SESSION['full_name']; ?>
</p>

<div class="card" style="max-width:250px;margin-bottom:20px;">

<h2>Total Job Cards</h2>

<h1><?php echo $totalJobCards['total']; ?></h1>

</div>

<form method="GET">

<input
type="text"
name="search"
placeholder="Search Job Card..."
value="<?php echo htmlspecialchars($search); ?>">

<br><br>

<button class="btn btn-search">
🔍 Search
</button>

<a href="#" onclick="window.print()" class="btn btn-add">
🖨 Print Report
</a>

<a
href="../exports/export_job_cards.php?search=<?php echo urlencode($search); ?>"
class="btn btn-add">

📊 Export Excel

</a>

<a
href="../exports/export_job_card_pdf.php?search=<?php echo urlencode($search); ?>"
class="btn btn-add">

📄 Export PDF

</a>


</form>

<table>

<tr>

<th>Job Card</th>
<th>Customer</th>
<th>Asset No.</th>
<th>Technician</th>
<th>Status</th>
<th>Created</th>

</tr>

<?php

if(mysqli_num_rows($result)>0){

while($row=mysqli_fetch_assoc($result)){

?>

<tr>

<td><?php echo $row['job_card_number']; ?></td>

<td><?php echo $row['customer_name']; ?></td>

<td><?php echo $row['asset_number']; ?></td>

<td><?php echo $row['full_name']; ?></td>

<td><?php echo $row['status']; ?></td>

<td><?php echo date("d M Y", strtotime($row['created_at'])); ?></td>

</tr>

<?php

}

}else{

?>

<tr>

<td colspan="6" style="text-align:center;">
No Job Cards Found.
</td>

</tr>

<?php

}

?>

</table>

</div>

<?php include("../includes/footer.php"); ?>