<?php
session_start();

if (!isset($_SESSION['username'])) {
    header("Location: ../auth/login.php");
    exit();
}

include("../config/db.php");
include("../includes/header.php");
include("../includes/sidebar.php");
include("../includes/status_badge.php");

$search = "";

if(isset($_GET['search'])){
    $search = mysqli_real_escape_string($conn,$_GET['search']);
}

$sql = "SELECT

service_requests.*,
customers.customer_name,
machines.asset_number,
machines.machine_model,
technicians.full_name

FROM service_requests

LEFT JOIN customers
ON service_requests.customer_id = customers.id

LEFT JOIN machines
ON service_requests.machine_id = machines.id

LEFT JOIN technicians
ON service_requests.technician_id = technicians.id

WHERE

service_requests.request_number LIKE '%$search%'
OR customers.customer_name LIKE '%$search%'
OR machines.asset_number LIKE '%$search%'
OR technicians.full_name LIKE '%$search%'
OR service_requests.status LIKE '%$search%'

ORDER BY service_requests.request_date DESC";

$result = mysqli_query($conn,$sql);

$total = mysqli_query($conn,"SELECT COUNT(*) AS total FROM service_requests");
$totalRequests = mysqli_fetch_assoc($total);
?>

<div class="main-content">

<div class="report-header">

<img src="../assets/images/logo.png">

<h2>G3 SYSTEMS</h2>

<h3>Service Management System</h3>

<hr>

</div>

<h1>Service Request Report</h1>

<p>

<strong>Generated On:</strong>

<?php echo date("d F Y"); ?>

|

<?php echo date("h:i A"); ?>

<br>

<strong>Generated By:</strong>

<?php echo $_SESSION['full_name']; ?>

</p>

<div class="card" style="max-width:250px;margin-bottom:20px;">

<h2>Total Requests</h2>

<h1><?php echo $totalRequests['total']; ?></h1>

</div>

<form method="GET">

<input
type="text"
name="search"
placeholder="Search Request..."
value="<?php echo htmlspecialchars($search); ?>">

<br><br>

<button class="btn btn-search">

🔍 Search

</button>

<a href="#" onclick="window.print()" class="btn btn-add">

🖨 Print Report

</a>

</form>

<table>

<tr>

<th>Request No.</th>

<th>Customer</th>

<th>Asset No.</th>

<th>Model</th>

<th>Technician</th>

<th>Priority</th>

<th>Status</th>

<th>Date</th>

</tr>

<?php

if(mysqli_num_rows($result)>0){

while($row=mysqli_fetch_assoc($result)){

?>

<tr>

<td><?php echo $row['request_number']; ?></td>

<td><?php echo $row['customer_name']; ?></td>

<td><?php echo $row['asset_number']; ?></td>

<td><?php echo $row['machine_model']; ?></td>

<td><?php echo $row['full_name']; ?></td>

<td><?php echo $row['priority']; ?></td>

<td><?php echo $row['status']; ?></td>

<td><?php echo date("d M Y", strtotime($row['request_date'])); ?></td>

</tr>

<?php

}

}else{

?>

<tr>

<td colspan="8" style="text-align:center;">

No Service Requests Found.

</td>

</tr>

<?php

}

?>

</table>

</div>

<?php include("../includes/footer.php"); ?>