<?php
session_start();
require_once("../includes/permissions.php");
requireRole(['Manager']);

if (!isset($_SESSION['username'])) {
    header("Location: ../auth/login.php");
    exit();
}

include("../config/db.php");
/* Load Company Settings */

$settings_result = mysqli_query($conn, "SELECT * FROM settings WHERE id=1");
$settings = mysqli_fetch_assoc($settings_result);

$company_name = $settings['company_name'] ?? "G3 Systems";
$company_phone = $settings['company_phone'] ?? "";
$company_email = $settings['company_email'] ?? "";
$company_address = $settings['company_address'] ?? "";
include("../includes/header.php");
include("../includes/sidebar.php");
include("../includes/status_badge.php");

$search = "";

if(isset($_GET['search'])){
    $search = mysqli_real_escape_string($conn, $_GET['search']);
}

$sql = "SELECT *
FROM technicians
WHERE

full_name LIKE '%$search%'
OR phone LIKE '%$search%'
OR email LIKE '%$search%'
OR specialization LIKE '%$search%'
OR status LIKE '%$search%'

ORDER BY full_name ASC";

$result = mysqli_query($conn,$sql);

$total = mysqli_query($conn,"SELECT COUNT(*) AS total FROM technicians");
$totalTechnicians = mysqli_fetch_assoc($total);
?>

<div class="main-content">

<div class="report-header">

<img src="../assets/images/logo.png">

<h2><?php echo htmlspecialchars($company_name); ?></h2>

<h3>Service Management System</h3>

<?php if($company_phone != ""): ?>
<p>📞 <?php echo htmlspecialchars($company_phone); ?></p>
<?php endif; ?>

<?php if($company_email != ""): ?>
<p>✉️ <?php echo htmlspecialchars($company_email); ?></p>
<?php endif; ?>

<?php if($company_address != ""): ?>
<p>📍 <?php echo htmlspecialchars($company_address); ?></p>
<?php endif; ?>

<hr>

</div>

<h1>Technician Report</h1>

<p>

<strong>Generated On:</strong>

<?php echo date("d F Y"); ?>

|

<?php echo date("h:i A"); ?>

<br>

<strong>Generated By:</strong>

<?php echo $_SESSION['full_name']; ?>

</p>

<div class="card" style="max-width:250px;margin-bottom:20px;">

<h2>Total Technicians</h2>

<h1><?php echo $totalTechnicians['total']; ?></h1>

</div>

<form method="GET">

<input
type="text"
name="search"
placeholder="Search Technician..."
value="<?php echo htmlspecialchars($search); ?>">

<br><br>

<button class="btn btn-search">

🔍 Search

</button>

<a href="#" onclick="window.print()" class="btn btn-add">
🖨 Print Report
</a>

<a
href="../exports/export_technicians.php?search=<?php echo urlencode($search); ?>"
class="btn btn-add">

📊 Export Excel

</a>

<a
href="../exports/export_technicians_pdf.php?search=<?php echo urlencode($search); ?>"
class="btn btn-add">

📄 Export PDF

</a>

</form>

<table>

<tr>

<th>ID</th>

<th>Full Name</th>

<th>Phone</th>

<th>Email</th>

<th>Specialization</th>

<th>Status</th>

</tr>

<?php

if(mysqli_num_rows($result)>0){

while($row=mysqli_fetch_assoc($result)){

?>

<tr>

<td><?php echo $row['id']; ?></td>

<td><?php echo $row['full_name']; ?></td>

<td><?php echo $row['phone']; ?></td>

<td><?php echo $row['email']; ?></td>

<td><?php echo $row['specialization']; ?></td>

<td><?php echo $row['status']; ?></td>

</tr>

<?php

}

}else{

?>

<tr>

<td colspan="6" style="text-align:center;">

No Technicians Found.

</td>

</tr>

<?php

}

?>

</table>

</div>

<?php include("../includes/footer.php"); ?>