<?php

session_start();

require_once("../includes/permissions.php");
requireRole(['Manager']);

if (!isset($_SESSION['username'])) {
    header("Location: ../auth/login.php");
    exit();
}

include("../config/db.php");


// ==============================
// Excel Headers
// ==============================

header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=technician_report.xls");
header("Pragma: no-cache");
header("Expires: 0");


// ==============================
// Search
// ==============================

$search = "";

if (isset($_GET['search'])) {

    $search = mysqli_real_escape_string(
        $conn,
        $_GET['search']
    );

}


// ==============================
// Technician Query
// ==============================

$sql = "SELECT
            id,
            full_name,
            phone,
            email,
            specialization,
            status

        FROM technicians

        WHERE
            full_name LIKE '%$search%'
            OR phone LIKE '%$search%'
            OR email LIKE '%$search%'
            OR specialization LIKE '%$search%'
            OR status LIKE '%$search%'

        ORDER BY full_name ASC";


$result = mysqli_query($conn, $sql);


// ==============================
// Report Title
// ==============================

echo "G3 Systems - Technician Report\n";
echo "Generated By: " . $_SESSION['full_name'] . "\n";
echo "Generated On: " . date("d F Y h:i A") . "\n";
echo "\n";


// ==============================
// Table Headers
// ==============================

echo "ID\tFull Name\tPhone\tEmail\tSpecialization\tStatus\n";


// ==============================
// Data
// ==============================

while ($row = mysqli_fetch_assoc($result)) {

    echo
        $row['id'] . "\t" .
        $row['full_name'] . "\t" .
        $row['phone'] . "\t" .
        $row['email'] . "\t" .
        $row['specialization'] . "\t" .
        $row['status'] . "\n";
}

?>