<?php

session_start();

require_once("../includes/permissions.php");
requireRole(['Manager']);

if (!isset($_SESSION['username'])) {
    header("Location: ../auth/login.php");
    exit();
}

include("../config/db.php");


// ==============================
// Excel Headers
// ==============================

header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=service_request_report.xls");
header("Pragma: no-cache");
header("Expires: 0");


// ==============================
// Search
// ==============================

$search = "";

if (isset($_GET['search'])) {

    $search = mysqli_real_escape_string(
        $conn,
        $_GET['search']
    );

}


// ==============================
// Service Request Query
// ==============================

$sql = "SELECT

            service_requests.*,
            customers.customer_name,
            machines.asset_number,
            machines.machine_model,
            technicians.full_name

        FROM service_requests

        LEFT JOIN customers
            ON service_requests.customer_id = customers.id

        LEFT JOIN machines
            ON service_requests.machine_id = machines.id

        LEFT JOIN technicians
            ON service_requests.technician_id = technicians.id

        WHERE

            service_requests.request_number LIKE '%$search%'
            OR customers.customer_name LIKE '%$search%'
            OR machines.asset_number LIKE '%$search%'
            OR machines.machine_model LIKE '%$search%'
            OR technicians.full_name LIKE '%$search%'
            OR service_requests.priority LIKE '%$search%'
            OR service_requests.status LIKE '%$search%'

        ORDER BY service_requests.request_date DESC";


$result = mysqli_query($conn, $sql);


// ==============================
// Report Information
// ==============================

echo "G3 Systems - Service Request Report\n";

echo "Generated By: "
     . $_SESSION['full_name']
     . "\n";

echo "Generated On: "
     . date("d F Y h:i A")
     . "\n";

echo "\n";


// ==============================
// Table Headers
// ==============================

echo "Request No.\tCustomer\tAsset No.\tModel\tTechnician\tPriority\tStatus\tDate\n";


// ==============================
// Data
// ==============================

while ($row = mysqli_fetch_assoc($result)) {

    echo
        $row['request_number'] . "\t" .
        $row['customer_name'] . "\t" .
        $row['asset_number'] . "\t" .
        $row['machine_model'] . "\t" .
        $row['full_name'] . "\t" .
        $row['priority'] . "\t" .
        $row['status'] . "\t" .
        date("d M Y", strtotime($row['request_date'])) .
        "\n";
}

?>