<?php

session_start();

require_once("../includes/permissions.php");
requireRole(['Manager']);

if (!isset($_SESSION['username'])) {
    header("Location: ../auth/login.php");
    exit();
}

require_once("../config/db.php");
require_once("../vendor/autoload.php");

use Dompdf\Dompdf;
use Dompdf\Options;


// ==============================
// COMPANY SETTINGS
// ==============================

$settings_result = mysqli_query(
    $conn,
    "SELECT * FROM settings WHERE id=1"
);

$settings = mysqli_fetch_assoc($settings_result);

$company_name = $settings['company_name'] ?? "G3 Systems";
$company_phone = $settings['company_phone'] ?? "";
$company_email = $settings['company_email'] ?? "";
$company_address = $settings['company_address'] ?? "";


// ==============================
// SEARCH
// ==============================

$search = "";

if (isset($_GET['search'])) {

    $search = mysqli_real_escape_string(
        $conn,
        $_GET['search']
    );

}


// ==============================
// MACHINE DATA
// ==============================

$sql = "

SELECT
    machines.*,
    customers.customer_name

FROM machines

LEFT JOIN customers
    ON machines.customer_id = customers.id

WHERE

machines.asset_number LIKE '%$search%'

OR customers.customer_name LIKE '%$search%'

OR machines.machine_model LIKE '%$search%'

OR machines.brand LIKE '%$search%'

OR machines.serial_number LIKE '%$search%'

ORDER BY machines.asset_number ASC

";

$result = mysqli_query($conn, $sql);


// ==============================
// PDF HTML
// ==============================

$html = '

<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<style>

body {
    font-family: DejaVu Sans, sans-serif;
    font-size: 10px;
    color: #222;
}

.header {
    text-align: center;
    margin-bottom: 20px;
}

.logo {
    width: 90px;
    margin-bottom: 5px;
}

.company-name {
    font-size: 20px;
    font-weight: bold;
}

.system-name {
    font-size: 14px;
}

.contact {
    font-size: 10px;
    color: #555;
}

hr {
    border: none;
    border-top: 1px solid #777;
}

.report-title {
    text-align: center;
    font-size: 18px;
    font-weight: bold;
    margin-top: 20px;
}

.report-info {
    margin-top: 10px;
    margin-bottom: 15px;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 15px;
}

th {
    background-color: #eeeeee;
    font-weight: bold;
}

th,
td {
    border: 1px solid #777;
    padding: 6px;
    text-align: left;
}

.footer {
    margin-top: 25px;
    text-align: center;
    font-size: 9px;
    color: #777;
}

</style>

</head>

<body>

<div class="header">

<img src="data:image/png;base64,' .
base64_encode(
    file_get_contents(
        '../assets/images/logo.png'
    )
) .
'" class="logo">

<div class="company-name">' .
htmlspecialchars($company_name) .
'</div>

<div class="system-name">
Service Management System
</div>';

if ($company_phone != "") {

    $html .= '
    <div class="contact">
    Phone: ' .
    htmlspecialchars($company_phone) .
    '</div>';

}

if ($company_email != "") {

    $html .= '
    <div class="contact">
    Email: ' .
    htmlspecialchars($company_email) .
    '</div>';

}

if ($company_address != "") {

    $html .= '
    <div class="contact">
    Address: ' .
    htmlspecialchars($company_address) .
    '</div>';

}

$html .= '

<hr>

</div>

<div class="report-title">
Machine Report
</div>

<div class="report-info">

<strong>Generated On:</strong>
' . date("d F Y h:i A") . '

<br>

<strong>Generated By:</strong>
' .
htmlspecialchars($_SESSION['full_name']) .
'';

if ($search != "") {

    $html .= '

<br>

<strong>Search Filter:</strong>
' .
htmlspecialchars($search);

}

$html .= '

</div>

<table>

<tr>

<th>Asset No.</th>
<th>Customer</th>
<th>Brand</th>
<th>Model</th>
<th>Serial No.</th>
<th>Location</th>
<th>Status</th>
<th>Installed</th>

</tr>
';


// ==============================
// TABLE DATA
// ==============================

if (
    $result &&
    mysqli_num_rows($result) > 0
) {

    while ($row = mysqli_fetch_assoc($result)) {

        $html .= '

        <tr>

        <td>' .
        htmlspecialchars($row['asset_number']) .
        '</td>

        <td>' .
        htmlspecialchars($row['customer_name']) .
        '</td>

        <td>' .
        htmlspecialchars($row['brand']) .
        '</td>

        <td>' .
        htmlspecialchars($row['machine_model']) .
        '</td>

        <td>' .
        htmlspecialchars($row['serial_number']) .
        '</td>

        <td>' .
        htmlspecialchars($row['location']) .
        '</td>

        <td>' .
        htmlspecialchars($row['status']) .
        '</td>

        <td>' .
        htmlspecialchars($row['installation_date']) .
        '</td>

        </tr>

        ';

    }

} else {

    $html .= '

    <tr>

    <td colspan="8" style="text-align:center;">

    No Machines Found.

    </td>

    </tr>

    ';

}


$html .= '

</table>

<div class="footer">

G3 Service Management System
<br>
Generated automatically

</div>

</body>

</html>
';


// ==============================
// DOMPDF
// ==============================

$options = new Options();

$options->set(
    'isRemoteEnabled',
    true
);

$options->set(
    'defaultFont',
    'DejaVu Sans'
);

$dompdf = new Dompdf($options);

$dompdf->loadHtml($html);

$dompdf->setPaper(
    'A4',
    'landscape'
);

$dompdf->render();


// ==============================
// DOWNLOAD
// ==============================

$dompdf->stream(
    "machine_report.pdf",
    [
        "Attachment" => true
    ]
);

exit();

?>